version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
            - mongo
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
            - "MONGO_PORT=27017"
            - "MONGO_HOST=mongo"
    database:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=dockerApp"
        ports:
            - "33061:3306"
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"
    mongo:
        image: mongo:3.0
        ports:
            - "27017:27017"
